spring:
    profiles: 
        active: "localhost"
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/suiviStartupsIncubPE?currentSchema=piloti
        username: suiviStartupsIncubPE
        password: suiviStartupsIncubPE
    jpa:
        hibernate: 
            ddl-auto : none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
server:
    port: 8081
    error:
        include-message: always    

kanimstv:
    app:
        jwtSecret: kanimstvSecretKey
        jwtExpirationMs: 86400000